backend: tf
eval: 1000
early_stop: 30
epochs: 100
mod_list:
- flops_module
dataset: cifar100
name: results_FLEXIBO_controller/flexibo_cifar100_seed96_e1000_ep100
seed: 96
quantization: false
verbose: 2
w_flops: 0.3
w_HW: 0.33
lacc: 0.3
flops_th: 150000000
nparams_th: 15000000000
opt: RS
frames: 16
mode: fwdPass
channels: 2
polarity: both
init_random: 10
candidate_pool: 512
surrogate: GP
beta: 1.0
accuracy_cost: 1.0
flops_cost: 0.05
max_flops_only_streak: 5
flops_scale: null
resume: true
max_new_evals: 25
external_tuner: FlexiBO
search_space_source: RS
created_at: '2026-07-14T08:05:49'
